"""
Model training for distraction detection.

WORKFLOW:
1. Load features.csv (generated by features/compute_features.py)
2. Split into 80% train / 20% test
3. Train LightGBM classifier (100 trees, max_depth=5, lr=0.05)
4. Save model to model.pkl
5. Save feature config to feature_config.json

USAGE:
  python models/train.py
"""

import pandas as pd
import numpy as np
import joblib
import json
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    roc_auc_score,
    f1_score,
    precision_score,
    recall_score,
    classification_report,
    confusion_matrix
)
import lightgbm as lgb


def load_features(path: str = "features/features.csv") -> tuple:
    """
    Load features from CSV.

    Args:
        path: Path to features.csv

    Returns:
        (X, y, feature_names) where:
        - X: Feature matrix (numpy array)
        - y: Labels (numpy array)
        - feature_names: List of feature column names
    """
    print(f"📂 Loading features from {path}...")

    df = pd.read_csv(path)

    # Separate features from labels and metadata
    metadata_cols = ['window_start', 'window_end', 'label']
    feature_cols = [col for col in df.columns if col not in metadata_cols]

    X = df[feature_cols].values
    y = (df['label'] == 'distracted').astype(int).values  # 1 = distracted, 0 = focused

    print(f"  ✓ Loaded {len(df)} samples")
    print(f"  ✓ Features: {len(feature_cols)}")
    print(f"  ✓ Labels: {y.sum()} distracted, {len(y) - y.sum()} focused")

    # Handle NaN values (from windows with only 1 gaze frame)
    if np.isnan(X).any():
        print(f"  ⚠️  Found NaN values, filling with 0")
        X = np.nan_to_num(X, nan=0.0)

    return X, y, feature_cols


def train_model(X_train, y_train, X_test, y_test):
    """
    Train LightGBM classifier.

    Hyperparameters from blueprint:
    - n_estimators: 100 trees
    - max_depth: 5
    - learning_rate: 0.05

    Args:
        X_train: Training features
        y_train: Training labels
        X_test: Test features
        y_test: Test labels

    Returns:
        Trained LightGBM model
    """
    print("\n🤖 Training LightGBM classifier...")
    print(f"  Hyperparameters:")
    print(f"    - n_estimators: 100")
    print(f"    - max_depth: 5")
    print(f"    - learning_rate: 0.05")

    # Create model with blueprint hyperparameters
    model = lgb.LGBMClassifier(
        n_estimators=100,
        max_depth=5,
        learning_rate=0.05,
        random_state=42,
        verbose=-1  # Suppress training output
    )

    # Train
    model.fit(X_train, y_train)

    print(f"  ✓ Training complete!")

    # Evaluate on test set
    y_pred = model.predict(X_test)
    y_pred_proba = model.predict_proba(X_test)[:, 1]

    # Compute metrics
    auc = roc_auc_score(y_test, y_pred_proba)
    f1 = f1_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)

    print(f"\n📊 Test Set Performance:")
    print(f"  ROC-AUC:   {auc:.3f} (target: ≥0.80)")
    print(f"  F1 Score:  {f1:.3f} (target: ≥0.75)")
    print(f"  Precision: {precision:.3f}")
    print(f"  Recall:    {recall:.3f}")

    # Confusion matrix
    cm = confusion_matrix(y_test, y_pred)
    print(f"\n📈 Confusion Matrix:")
    print(f"             Predicted")
    print(f"           Focused  Distracted")
    print(f"  Focused    {cm[0][0]:3d}       {cm[0][1]:3d}")
    print(f"  Distracted {cm[1][0]:3d}       {cm[1][1]:3d}")

    # Classification report
    print(f"\n📋 Detailed Report:")
    print(classification_report(y_test, y_pred,
                                target_names=['Focused', 'Distracted']))

    return model, auc, f1


def save_model(model, feature_names, auc, f1):
    """
    Save trained model and configuration.

    Saves:
    - model.pkl: Serialized LightGBM model
    - feature_config.json: Feature names and metadata

    Args:
        model: Trained LightGBM model
        feature_names: List of feature column names
        auc: ROC-AUC score
        f1: F1 score
    """
    print(f"\n💾 Saving model...")

    # Save model
    model_path = "models/model.pkl"
    joblib.dump(model, model_path)
    print(f"  ✓ Model saved to {model_path}")

    # Save feature config (for inference later)
    config = {
        'feature_names': feature_names,
        'num_features': len(feature_names),
        'model_type': 'LightGBM',
        'metrics': {
            'roc_auc': float(auc),
            'f1_score': float(f1)
        },
        'hyperparameters': {
            'n_estimators': 100,
            'max_depth': 5,
            'learning_rate': 0.05
        }
    }

    config_path = "models/feature_config.json"
    with open(config_path, 'w') as f:
        json.dump(config, f, indent=2)
    print(f"  ✓ Config saved to {config_path}")


def main():
    """
    Main training pipeline.

    Steps:
    1. Load features
    2. Split train/test (80/20)
    3. Train LightGBM
    4. Evaluate on test set
    5. Save model
    """
    print("=" * 60)
    print("DIALED - Model Training")
    print("=" * 60)
    print()

    try:
        # 1. Load features
        X, y, feature_names = load_features("features/features.csv")

        # Check if we have enough data
        if len(X) < 10:
            print("\n⚠️  Warning: Very few samples!")
            print(f"   You have {len(X)} windows. Recommend at least 100.")
            print(f"   Model will likely overfit.")
            response = input("\nContinue anyway? (y/n): ")
            if response.lower() != 'y':
                print("Aborting. Collect more data first!")
                return

        # 2. Split train/test
        print(f"\n📊 Splitting data (80% train, 20% test)...")
        X_train, X_test, y_train, y_test = train_test_split(
            X, y,
            test_size=0.2,
            random_state=42,
            stratify=y  # Maintain class balance
        )

        print(f"  ✓ Train set: {len(X_train)} samples")
        print(f"  ✓ Test set:  {len(X_test)} samples")

        # 3. Train model
        model, auc, f1 = train_model(X_train, y_train, X_test, y_test)

        # 4. Save model
        save_model(model, feature_names, auc, f1)

        # 5. Success message
        print(f"\n✅ SUCCESS!")
        print(f"\n   Model trained and saved!")
        print(f"   ROC-AUC: {auc:.3f}")
        print(f"   F1 Score: {f1:.3f}")
        print(f"\n🎯 Next steps:")
        print(f"   1. Run: python models/evaluate.py (to see feature importance)")
        print(f"   2. Collect more data to improve metrics")
        print(f"   3. Build demo script for real-time predictions")

    except FileNotFoundError:
        print("\n❌ Error: features.csv not found!")
        print("   Run this first: python features/compute_features.py")

    except Exception as e:
        print(f"\n❌ Error: {e}")
        import traceback
        traceback.print_exc()


if __name__ == "__main__":
    main()
